[[redirects]]
  from = "/api/*"
  to = "http://18.188.234.162:8000/api/:splat"
  status = 200
  force = true
  
[[redirects]]
  from = "/ask/*"
  to = "http://18.188.234.162:8000/ask/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/health"
  to = "http://18.188.234.162:8000/health"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200